### ISSUE TITLE
Can't install on bitnami redmine

### ISSUE THREAD

**Issue by hanh45** [Hopebaytech/redmine_mail_reminder#31]
Hello master,
I try install redmine_mail_reminder on bitnami redmine but i can't migrate
Please help me fix with this issue. Thank you very much!
Bitnami redmine download at: https://bitnami.com/stack/redmine
Redmine Version: 3.0.2
Trace log:
```
ruby bin/rake redmine:plugins RAILS_ENV=production --trace
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.0/lib/bundler/runtime.rb:222: warning: Insecure world writable dir /vsmsc/deploy/environment/jdk1.7.0_21 in PATH, mode 040777
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
** Invoke redmine:plugins (first_time)
** Execute redmine:plugins
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
LoadError: cannot load such file -- action_view/vendor/html-scanner
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/prototype-rails-4.0.1/lib/prototype-rails/selector_assertions.rb:2:in `<top (required)>'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/prototype-rails-4.0.1/lib/prototype-rails/on_load_action_controller.rb:1:in `<top (required)>'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/prototype-rails-4.0.1/lib/prototype-rails.rb:8:in `block (2 levels) in <class:Engine>'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:27:in `each'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/prototype-rails-4.0.1/lib/prototype-rails.rb:7:in `block in <class:Engine>'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/2.0.0/tsort.rb:180:in `each'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
/home/***/redmine-3.0.2-0/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/application.rb:328:in `require_environment!'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:199:in `each'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/home/***/redmine-3.0.2-0/apps/redmine/htdocs/lib/tasks/redmine.rake:52:in `block (2 levels) in <top (required)>'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/home/***/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
bin/rake:16:in `load'
bin/rake:16:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```

**Comment by Androc** [comment]
Not sure if it is your problem but you ran `rake redmine:plugins` it should be `rake redmine:plugins:migrate`.

I searched for your problem in Google and found that it is often solved by using `gem 'prototype-rails', github: 'rails/prototype-rails', branch: '4.2'` inside the Gemfile but it is already done in master branch.

You use master branch, right ?

**Comment by hanh45** [comment]
Hello master,
I install with step by step:
1. Download redmine_mail_reminder from master branch: https://github.com/Hopebaytech/redmine_mail_reminder
2. Upload to plugin folder, unzip and rename to: redmine_mail_reminder
3. Run in bitnami environment with commands:
    - bundle install --without development test postgresql sqlite --no-deployment:   OK
    - ruby bin/rake redmine:plugins RAILS_ENV=production: error as above
4. About prototype-rails:
My server is not connect to internet.
I can't use in Gemfile: gem 'prototype-rails', github: 'rails/prototype-rails', branch: '4.2' 
I install prototype-rails on local.
- I install version 4.0.1: error as above
- I was download prototype-rails from: https://github.com/rails/prototype-rails/tree/4.2
   - After build with command: gem build prototype-rails.gemspec
   - I receipt prototype-rails-4.0.0.gem ???
  I can't install prototype-rails version 4.2

**Comment by jcppkkk** [comment]
https://github.com/rails/prototype-rails/blob/4.2/prototype-rails.gemspec
I think that's because prototype-rails 4.2 branch is under developing. The gem should be able to install with rails 4.2 even though the version number is not updated.

**Comment by hanh45** [comment]
Thanks for support!
After build and install true prototype-rails version, i was install success redmine_mail_reminder plugin
