### ISSUE TITLE
NoMethodError when running "rake reminder:exec RAILS_ENV=production"

### ISSUE THREAD

**Issue by rmull** [Hopebaytech/redmine_mail_reminder#51]
```
** Invoke reminder:exec (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute reminder:exec
Project "My Proj 1" with query "My Overdue Issues"         is processing.
Project "My Proj 2" with query "My Overdue Issues"   is processing.
Project "My Proj 3" with query "My Overdue Issues"    is processing.
rake aborted!
NoMethodError: undefined method `enabled_module_names' for nil:NilClass
/var/www/html/issues/plugins/redmine_mail_reminder/lib/tasks/reminder.rake:8:in `block (3 levels) in <top (required)>'
/var/www/html/issues/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation/query_methods.rb:251:in `block in select'
/var/www/html/issues/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation/query_methods.rb:251:in `select'
/var/www/html/issues/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation/query_methods.rb:251:in `select'
/var/www/html/issues/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/querying.rb:10:in `select'
/var/www/html/issues/plugins/redmine_mail_reminder/lib/tasks/reminder.rake:7:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => reminder:exec
```

I have a number of other plugins installed - could this be some sort of conflict? Is there anything I can do to help debug? I am not familiar with the Ruby or Rails development environments.

Redmine 3.1.1, rake 10.4.2, ruby ruby 2.1.5p273

**Comment by rmull** [comment]
I am now thinking that this may have something to do with having deleted projects in my Redmine installation. I am trying to learn enough Ruby to help me explore that possibility.

**Comment by rmull** [comment]
I think I have fixed this by testing if the project being checked is nil or not. Please verify that I am doing the right thing.

```
diff --git a/lib/tasks/reminder.rake b/lib/tasks/reminder.rake
index a1d2bb5..5dccbb5 100644
--- a/lib/tasks/reminder.rake
+++ b/lib/tasks/reminder.rake
@@ -5,19 +5,21 @@ namespace :reminder do
     require 'colorize'
     mail_data = Hash.new{|h, k| h[k] = Set.new}
     reminders = MailReminder.select do |rem|
-      next(false) until rem.project.enabled_module_names.include?('issue_reminder')
-      next(false) until rem.query.present?
-      print "Project \"#{ rem.project.name }\" with query \"#{ rem.query.name }\" "
-      if args.test == "test"
-        puts "\t is forced processing under [test] mode.".yellow
-        next(true)
-      end
-      if rem.execute?
-        puts "\t is processing.".light_blue
-        next(true)
-      else
-        puts "\t is ignored. It's executed recently and too early for next execution.".red
-        next(false)
+      if rem.project
+        next(false) until rem.project.enabled_module_names.include?('issue_reminder')
+        next(false) until rem.query.present?
+        print "Project \"#{ rem.project.name }\" with query \"#{ rem.query.name }\" "
+        if args.test == "test"
+          puts "\t is forced processing under [test] mode.".yellow
+          next(true)
+        end
+        if rem.execute?
+          puts "\t is processing.".light_blue
+          next(true)
+        else
+          puts "\t is ignored. It's executed recently and too early for next execution.".red
+          next(false)
+        end
       end
     end
     reminders.
```
