### ISSUE TITLE
migrate error on redmine-3.3.0

### ISSUE THREAD

**Issue by leaver** [Hopebaytech/redmine_mail_reminder#73]
the error info:
```
D:\App\Bitnami\redmine-3.3.0-0\apps\redmine\htdocs\plugins\redmine_mail_reminder
>**bundle exec rake reminder:exec RAILS_ENV="production"**
(in D:/App/Bitnami/redmine-3.3.0-0/apps/redmine/htdocs)
rake aborted!
NameError: uninitialized constant ActionDispatch::XmlParamsParser
D:/App/Bitnami/redmine-3.3.0-0/apps/redmine/htdocs/config/application.rb:55:in `
<class:Application>'
D:/App/Bitnami/redmine-3.3.0-0/apps/redmine/htdocs/config/application.rb:8:in `<
module:RedmineApp>'
D:/App/Bitnami/redmine-3.3.0-0/apps/redmine/htdocs/config/application.rb:7:in `<
top (required)>'
D:/App/Bitnami/redmine-3.3.0-0/apps/redmine/htdocs/Rakefile:5:in `require'
D:/App/Bitnami/redmine-3.3.0-0/apps/redmine/htdocs/Rakefile:5:in `<top (required
)>'
(See full trace by running task with --trace)
```
gem list:

> *** LOCAL GEMS ***

actionmailer (4.2.6)
actionpack (4.2.6)
actionpack-xml_parser (1.0.2)
actionview (4.2.6)
activejob (4.2.6)
activemodel (4.2.6)
activerecord (4.2.6)
activesupport (4.2.6)
addressable (2.4.0)
arel (6.0.3)
bigdecimal (1.2.4)
builder (3.2.2)
bundler (1.9.6)
colorize (0.8.1)
concurrent-ruby (1.0.3.pre3, 1.0.2)
css_parser (1.4.5)
erubis (2.7.0)
fastercsv (1.5.5)
globalid (0.3.6)
htmlentities (4.3.4)
i18n (0.7.0)
io-console (0.4.3)
json (1.8.3, 1.8.1)
loofah (2.0.3)
mail (2.6.4)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_portile2 (2.1.0)
minitest (5.9.0, 4.7.5)
nokogiri (1.6.8 x86-mingw32)
pkg-config (1.1.7)
premailer (1.8.7, 1.8.6)
premailer-rails (1.9.3)
prototype-rails (4.0.0)
psych (2.0.5)
rack (1.6.4)
rack-test (0.6.3)
rails (4.2.6)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.3)
railties (4.2.6)
rake (11.2.2, 10.1.0)
rdoc (4.1.0)
sprockets (3.6.3)
sprockets-rails (3.1.1)
test-unit (2.1.8.0)
thor (0.19.1)
thread_safe (0.3.5)
tzinfo 

> (1.2.2)

**Comment by jwbearden** [comment]
Is this working on 3.3?

**Comment by eckucukoglu** [comment]
Yes, actually it does.

I'm using this plugin on **redmine 3.3**, ruby 2.0, rails 4.2.6 w/o any errors.
