### ISSUE TITLE
error message: There was an error parsing `Gemfile

### ISSUE THREAD

**Issue by u2mike** [Hopebaytech/redmine_mail_reminder#83]
hello 

i get the following error message during activating this plugin:

any workaround ?
thanks
michael

[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: nokogiri (>= 1.6.7.2) and nokogiri (~> 1.6.8). Bundler cannot continue.

 #  from /opt/redmine-3.3.2-2/apps/redmine/htdocs/plugins/redmine_mail_reminder/Gemfile:6
 #  -------------------------------------------
 #  gem 'premailer-rails'
 >  gem "nokogiri", "~> 1.6.8"
 #
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /opt/redmine-3.3.2-2/apps/redmine/htdocs/Gemfile:118
 #  -------------------------------------------
 #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
 >    eval_gemfile file
 #  end
 #  -------------------------------------------

**Comment by u2mike** [comment]
can anybody help in this issue?

**Comment by u2mike** [comment]
```
i changed the gemfile but now i get the following error when i run a task:

any hint?

.../htdocs/bin/rake -f .../htdocs/Rakefile reminder:exec RAILS_ENV=production
############### cut ####################
Project "ELOGWMS" with query "11_remi_due_date_any"      is ignored. It's executed recently and too early for next execution.
Project "ELOGWMS" with query "11_remi_due_date_any"      is ignored. It's executed recently and too early for next execution.
Project "INFRASTRUKTUR" with query "11_remi_due_date_any"        is ignored. It's executed recently and too early for next execution.
Project "INFRASTRUKTUR" with query "11_remi_due_date_any"        is ignored. It's executed recently and too early for next execution.
Project "SAP" with query "11_remi_due_date_any"          is ignored. It's executed recently and too early for next execution.
Project "SAP" with query "11_remi_due_date_any"          is processing.
rake aborted!
Premailer::Rails::CSSHelper::FileNotFound: File with URL "/stylesheets/application.css" could not be loaded by any strategy.
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.9.5/lib/premailer/rails/css_helper.rb:45:in `load_css'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.9.5/lib/premailer/rails/css_helper.rb:21:in `css_for_url'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.9.5/lib/premailer/rails/css_helper.rb:17:in `block in css_for_doc'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.9.5/lib/premailer/rails/css_helper.rb:17:in `map'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.9.5/lib/premailer/rails/css_helper.rb:17:in `css_for_doc'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.9.5/lib/premailer/rails/customized_premailer.rb:14:in `initialize'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.9.5/lib/premailer/rails/hook.rb:97:in `new'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.9.5/lib/premailer/rails/hook.rb:97:in `premailer'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.9.5/lib/premailer/rails/hook.rb:86:in `generate_text_part'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.9.5/lib/premailer/rails/hook.rb:62:in `generate_alternative_part'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.9.5/lib/premailer/rails/hook.rb:50:in `generate_html_part_replacement'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.9.5/lib/premailer/rails/hook.rb:24:in `perform'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.9.5/lib/premailer/rails/hook.rb:8:in `perform'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/mail-2.6.4/lib/mail/mail.rb:243:in `block in inform_interceptors'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/mail-2.6.4/lib/mail/mail.rb:242:in `each'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/mail-2.6.4/lib/mail/mail.rb:242:in `inform_interceptors'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/mail-2.6.4/lib/mail/message.rb:225:in `inform_interceptors'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/mail-2.6.4/lib/mail/message.rb:235:in `deliver'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/config/initializers/10-patches.rb:163:in `deliver'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/plugins/redmine_mail_reminder/lib/tasks/reminder.rake:43:in `block (4 levels) in <top (required)>'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/plugins/redmine_mail_reminder/lib/tasks/reminder.rake:42:in `each'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/plugins/redmine_mail_reminder/lib/tasks/reminder.rake:42:in `block (3 levels) in <top (required)>'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/plugins/redmine_mail_reminder/app/models/mail_reminder_mailer.rb:23:in `with_synched_deliveries'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/plugins/redmine_mail_reminder/lib/tasks/reminder.rake:41:in `block (2 levels) in <top (required)>'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => reminder:exec
(See full trace by running task with --trace)
############# cut ##############
```

**Comment by reyeztom** [comment]
Same issue overhere.
Can anyone help us what to do?

**Comment by jwbearden** [comment]
Same here...

**Comment by u2mike** [comment]
once more ... can anyone assist with this issue?
thanks in advance

**Comment by u2mike** [comment]
have anybody a workaround in this case

**Comment by BRUTEF0RCE** [comment]
Same here! Anybody found a fix for this?
